//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    
    public partial class CategoriaRemedio
    {
        public string Categoria { get; set; }
        public string Nome { get; set; }
        public string Apresentacao { get; set; }
        public Nullable<bool> Humano { get; set; }
        public int Quantidade { get; set; }
        public string Unidade { get; set; }
        public Nullable<bool> Veterinario { get; set; }
    }
}
