//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remedio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Remedio()
        {
            this.Principios = new ObservableListSource<Principio>();
            this.Categorias = new ObservableListSource<Categoria>();
            this.Indicacoes = new ObservableListSource<Indicacao>();
        }
    
        public int ID { get; set; }
        public string Nome { get; set; }
        public string Apresentacao { get; set; }
        public int Quantidade { get; set; }
        public string Unidade { get; set; }
        public string Bula { get; set; }
        public string Link { get; set; }
        public Nullable<bool> Veterinario { get; set; }
        public Nullable<bool> Humano { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<Principio> Principios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<Categoria> Categorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<Indicacao> Indicacoes { get; set; }
    }
}
